[package]
name = "shape-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
imageproc = "0.23.0"
tinyrand = "0.5.0"
